### ISSUE TITLE
Update content for Scrollytelling Series to Human Atlas Stories content

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-previews#9]
# Replace Scrollytelling Series content with Human Atlas Stories content

## To Do

- [x] Remove old content in [Scrollytelling Series preview](https://hubmapconsortium.github.io/hra-previews/pilots/pilot4.html) and replace it with the new content in the [Human Atlas Stories document](https://docs.google.com/document/d/10aPX_6Vca8-GYJ532C8V5YDVnQbyW3eRjLQTvzYS2tA/edit#).

## Relevant Correspondence
![image](https://github.com/hubmapconsortium/hra-previews/assets/97060856/24a51678-ab68-4ca3-aefe-42f95ff9687a)

**Comment by LibbyUX** [comment]
@bhushankhope can you please update this preview content as soon as possible? 

@bherr2 can help if you need assistance with the technical details. Thanks so much!

**Comment by bhushankhope** [comment]
All the requested changes are done and are live.

**Comment by LibbyUX** [comment]
Looks great, thank you @bhushankhope!
